// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAd2lc0kQpemWDk1VFQYeaH6xgpatgJh8',
    appId: '1:1096902431580:web:ebf539da777f465588a799',
    messagingSenderId: '1096902431580',
    projectId: 'jfjewel-7cd8f',
    authDomain: 'jfjewel-7cd8f.firebaseapp.com',
    storageBucket: 'jfjewel-7cd8f.appspot.com',
    measurementId: 'G-R4CCJ5GT58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaw4VRNlwGwj2su-Zv9J-YSb0d9FIfZPU',
    appId: '1:1096902431580:android:503c7938f24a31b988a799',
    messagingSenderId: '1096902431580',
    projectId: 'jfjewel-7cd8f',
    storageBucket: 'jfjewel-7cd8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTWER40ec4uoqwh41z2CQ1eHWSlAH0wu4',
    appId: '1:1096902431580:ios:6c45b14a90feb37488a799',
    messagingSenderId: '1096902431580',
    projectId: 'jfjewel-7cd8f',
    storageBucket: 'jfjewel-7cd8f.appspot.com',
    iosClientId: '1096902431580-4p01t5c44rmaftceiakbu11tfl8qq0b6.apps.googleusercontent.com',
    iosBundleId: 'com.vistech.wimbo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTWER40ec4uoqwh41z2CQ1eHWSlAH0wu4',
    appId: '1:1096902431580:ios:8c99c3660282f52588a799',
    messagingSenderId: '1096902431580',
    projectId: 'jfjewel-7cd8f',
    storageBucket: 'jfjewel-7cd8f.appspot.com',
    iosClientId: '1096902431580-7on1lhlq13c73r021mbjej4gv4ur2ua4.apps.googleusercontent.com',
    iosBundleId: 'com.example.vistech',
  );
}
