// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4oN1yOrXQlMiQMPo3tjRAxp4lkhJwCqI',
    appId: '1:655617181482:web:105c104982879c9c0b4053',
    messagingSenderId: '655617181482',
    projectId: 'forexsomo',
    authDomain: 'forexsomo.firebaseapp.com',
    storageBucket: 'forexsomo.appspot.com',
    measurementId: 'G-V3R272C05M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASwUQBJ3WDa_jjmVAeChe6OlxetQI0cqk',
    appId: '1:655617181482:android:14aff959f4daaef30b4053',
    messagingSenderId: '655617181482',
    projectId: 'forexsomo',
    storageBucket: 'forexsomo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo4_LeM3fIusLaYhBypmwvBGhYM9FbVks',
    appId: '1:655617181482:ios:09427c1ccc3ac17a0b4053',
    messagingSenderId: '655617181482',
    projectId: 'forexsomo',
    storageBucket: 'forexsomo.appspot.com',
    iosClientId: '655617181482-c10chobs52jrnouq2ittaigjeba5niov.apps.googleusercontent.com',
    iosBundleId: 'com.ekaleerwe.forexsomo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo4_LeM3fIusLaYhBypmwvBGhYM9FbVks',
    appId: '1:655617181482:ios:eb2d5785c3412f320b4053',
    messagingSenderId: '655617181482',
    projectId: 'forexsomo',
    storageBucket: 'forexsomo.appspot.com',
    iosClientId: '655617181482-j9249eevcdqsdgs276oqq5bi9lno2vfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.vistech',
  );
}
